spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    database-platform: org.hibernate.dialect.MariaDBDialect
  mail:
    email_from: noreply@e-commune.net
    email_to: contact@e-commune.net
    host: smtp.hostinger.com
    port: 465
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl.enable: true              # Changed from starttls.enable
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
  datasource:
    url: jdbc:mysql://${DATABASE_HOSTNAME}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PWD}
  
api:
  key: ${API_KEY}

encryption:
  secret-key: ${ENCRYPTION_SECRET_KEY}

samory:
  urls:
    site: https://api-ecommune.samory.army
